### PR TITLE
add composer file

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by frugan-dev** [comment]
Hi @rubo77, i've fix composer namespace and synchronized `fix_mysql.inc.php` with the latest changes you made.
Could you please accept the pull request?

**Comment by frugan-dev** [comment]
This way you can include it via composer:

_composer.json_
```json
{
    "name": "<vendor>/<project>",
    "minimum-stability": "dev",
    "require": {
        "rubo77/php-mysql-fix": "dev-master"
    },
    "autoload": {
        "files": [
            "vendor/rubo77/php-mysql-fix/fix_mysql.inc.php"
        ]
    }
}
```

**Comment by rubo77** [comment]
I merged it like it is, although I wonder why  "platform":   "php": "7.0"?

If 8.2 is possible, please create a new PR (from a clean pull of the actual master)

**Comment by frugan-dev** [comment]
@rubo77 I think `platform` is an oversight and maybe it would be better to remove it, so that the real version of php is detected, what do you think?

**Comment by rubo77** [comment]
I don't use composer.

Just do what you think is best. I will add it. 

Also add some instructions in the readme please

**Comment by rubo77** [comment]
https://packagist.org/packages/rubo77/php-mysql-fix

**Pull request merged**
